// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by a Microsoft Visual Studio Team System 2005.
//        Runtime Version:2.0.41020.0
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//    
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.QualityTools.UnitTesting.Framework;

namespace AuroraUnitTests
{
public class BaseAccessor {
    
    protected Microsoft.VisualStudio.QualityTools.UnitTesting.Framework.PrivateObject m_privateObject;
    
    public BaseAccessor(object target, Microsoft.VisualStudio.QualityTools.UnitTesting.Framework.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.QualityTools.UnitTesting.Framework.PrivateObject(target, type);
    }
    
    public virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}


public class Aurora_ColourAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.QualityTools.UnitTesting.Framework.PrivateType m_privateType = new Microsoft.VisualStudio.QualityTools.UnitTesting.Framework.PrivateType(typeof(global::Aurora.Colour));
    
    public Aurora_ColourAccessor(global::Aurora.Colour target) : 
            base(target, m_privateType) {
    }
    
    public double red {
        get {
            double ret = ((double)(m_privateObject.GetField("red")));
            return ret;
        }
        set {
            m_privateObject.SetField("red", value);
        }
    }
    
    public double green {
        get {
            double ret = ((double)(m_privateObject.GetField("green")));
            return ret;
        }
        set {
            m_privateObject.SetField("green", value);
        }
    }
    
    public double blue {
        get {
            double ret = ((double)(m_privateObject.GetField("blue")));
            return ret;
        }
        set {
            m_privateObject.SetField("blue", value);
        }
    }
    
    public static global::Aurora.Colour AliceBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("AliceBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("AliceBlue", value);
        }
    }
    
    public static global::Aurora.Colour AntiqueWhite {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("AntiqueWhite")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("AntiqueWhite", value);
        }
    }
    
    public static global::Aurora.Colour Aqua {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Aqua")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Aqua", value);
        }
    }
    
    public static global::Aurora.Colour Aquamarine {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Aquamarine")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Aquamarine", value);
        }
    }
    
    public static global::Aurora.Colour Azure {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Azure")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Azure", value);
        }
    }
    
    public static global::Aurora.Colour Beige {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Beige")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Beige", value);
        }
    }
    
    public static global::Aurora.Colour Bisque {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Bisque")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Bisque", value);
        }
    }
    
    public static global::Aurora.Colour Black {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Black")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Black", value);
        }
    }
    
    public static global::Aurora.Colour BlanchedAlmond {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("BlanchedAlmond")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("BlanchedAlmond", value);
        }
    }
    
    public static global::Aurora.Colour Blue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Blue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Blue", value);
        }
    }
    
    public static global::Aurora.Colour BlueViolet {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("BlueViolet")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("BlueViolet", value);
        }
    }
    
    public static global::Aurora.Colour Brown {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Brown")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Brown", value);
        }
    }
    
    public static global::Aurora.Colour BurlyWood {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("BurlyWood")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("BurlyWood", value);
        }
    }
    
    public static global::Aurora.Colour CadetBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("CadetBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("CadetBlue", value);
        }
    }
    
    public static global::Aurora.Colour Chartreuse {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Chartreuse")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Chartreuse", value);
        }
    }
    
    public static global::Aurora.Colour Chocolate {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Chocolate")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Chocolate", value);
        }
    }
    
    public static global::Aurora.Colour Coral {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Coral")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Coral", value);
        }
    }
    
    public static global::Aurora.Colour CornflowerBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("CornflowerBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("CornflowerBlue", value);
        }
    }
    
    public static global::Aurora.Colour Cornsilk {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Cornsilk")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Cornsilk", value);
        }
    }
    
    public static global::Aurora.Colour Crimson {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Crimson")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Crimson", value);
        }
    }
    
    public static global::Aurora.Colour Cyan {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Cyan")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Cyan", value);
        }
    }
    
    public static global::Aurora.Colour DarkBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkBlue", value);
        }
    }
    
    public static global::Aurora.Colour DarkCyan {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkCyan")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkCyan", value);
        }
    }
    
    public static global::Aurora.Colour DarkGoldenrod {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkGoldenrod")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkGoldenrod", value);
        }
    }
    
    public static global::Aurora.Colour DarkGray {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkGray")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkGray", value);
        }
    }
    
    public static global::Aurora.Colour DarkGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkGreen", value);
        }
    }
    
    public static global::Aurora.Colour DarkKhaki {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkKhaki")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkKhaki", value);
        }
    }
    
    public static global::Aurora.Colour DarkMagenta {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkMagenta")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkMagenta", value);
        }
    }
    
    public static global::Aurora.Colour DarkOliveGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkOliveGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkOliveGreen", value);
        }
    }
    
    public static global::Aurora.Colour DarkOrange {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkOrange")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkOrange", value);
        }
    }
    
    public static global::Aurora.Colour DarkOrchid {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkOrchid")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkOrchid", value);
        }
    }
    
    public static global::Aurora.Colour DarkRed {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkRed")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkRed", value);
        }
    }
    
    public static global::Aurora.Colour DarkSalmon {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkSalmon")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkSalmon", value);
        }
    }
    
    public static global::Aurora.Colour DarkSeaGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkSeaGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkSeaGreen", value);
        }
    }
    
    public static global::Aurora.Colour DarkSlateBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkSlateBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkSlateBlue", value);
        }
    }
    
    public static global::Aurora.Colour DarkSlateGray {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkSlateGray")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkSlateGray", value);
        }
    }
    
    public static global::Aurora.Colour DarkTurquoise {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkTurquoise")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkTurquoise", value);
        }
    }
    
    public static global::Aurora.Colour DarkViolet {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DarkViolet")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DarkViolet", value);
        }
    }
    
    public static global::Aurora.Colour DeepPink {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DeepPink")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DeepPink", value);
        }
    }
    
    public static global::Aurora.Colour DeepSkyBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DeepSkyBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DeepSkyBlue", value);
        }
    }
    
    public static global::Aurora.Colour DimGray {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DimGray")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DimGray", value);
        }
    }
    
    public static global::Aurora.Colour DodgerBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("DodgerBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("DodgerBlue", value);
        }
    }
    
    public static global::Aurora.Colour FireBrick {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("FireBrick")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("FireBrick", value);
        }
    }
    
    public static global::Aurora.Colour FloralWhite {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("FloralWhite")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("FloralWhite", value);
        }
    }
    
    public static global::Aurora.Colour ForestGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("ForestGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("ForestGreen", value);
        }
    }
    
    public static global::Aurora.Colour Fuchsia {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Fuchsia")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Fuchsia", value);
        }
    }
    
    public static global::Aurora.Colour Gainsboro {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Gainsboro")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Gainsboro", value);
        }
    }
    
    public static global::Aurora.Colour GhostWhite {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("GhostWhite")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("GhostWhite", value);
        }
    }
    
    public static global::Aurora.Colour Gold {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Gold")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Gold", value);
        }
    }
    
    public static global::Aurora.Colour Goldenrod {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Goldenrod")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Goldenrod", value);
        }
    }
    
    public static global::Aurora.Colour Gray {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Gray")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Gray", value);
        }
    }
    
    public static global::Aurora.Colour Green {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Green")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Green", value);
        }
    }
    
    public static global::Aurora.Colour GreenYellow {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("GreenYellow")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("GreenYellow", value);
        }
    }
    
    public static global::Aurora.Colour Honeydew {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Honeydew")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Honeydew", value);
        }
    }
    
    public static global::Aurora.Colour HotPink {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("HotPink")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("HotPink", value);
        }
    }
    
    public static global::Aurora.Colour IndianRed {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("IndianRed")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("IndianRed", value);
        }
    }
    
    public static global::Aurora.Colour Indigo {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Indigo")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Indigo", value);
        }
    }
    
    public static global::Aurora.Colour Ivory {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Ivory")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Ivory", value);
        }
    }
    
    public static global::Aurora.Colour Khaki {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Khaki")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Khaki", value);
        }
    }
    
    public static global::Aurora.Colour Lavender {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Lavender")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Lavender", value);
        }
    }
    
    public static global::Aurora.Colour LavenderBlush {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LavenderBlush")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LavenderBlush", value);
        }
    }
    
    public static global::Aurora.Colour LawnGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LawnGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LawnGreen", value);
        }
    }
    
    public static global::Aurora.Colour LemonChiffon {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LemonChiffon")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LemonChiffon", value);
        }
    }
    
    public static global::Aurora.Colour LightBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightBlue", value);
        }
    }
    
    public static global::Aurora.Colour LightCoral {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightCoral")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightCoral", value);
        }
    }
    
    public static global::Aurora.Colour LightCyan {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightCyan")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightCyan", value);
        }
    }
    
    public static global::Aurora.Colour LightGoldenrodYellow {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightGoldenrodYellow")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightGoldenrodYellow", value);
        }
    }
    
    public static global::Aurora.Colour LightGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightGreen", value);
        }
    }
    
    public static global::Aurora.Colour LightGrey {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightGrey")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightGrey", value);
        }
    }
    
    public static global::Aurora.Colour LightPink {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightPink")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightPink", value);
        }
    }
    
    public static global::Aurora.Colour LightSalmon {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightSalmon")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightSalmon", value);
        }
    }
    
    public static global::Aurora.Colour LightSeaGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightSeaGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightSeaGreen", value);
        }
    }
    
    public static global::Aurora.Colour LightSkyBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightSkyBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightSkyBlue", value);
        }
    }
    
    public static global::Aurora.Colour LightSlateGray {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightSlateGray")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightSlateGray", value);
        }
    }
    
    public static global::Aurora.Colour LightSteelBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightSteelBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightSteelBlue", value);
        }
    }
    
    public static global::Aurora.Colour LightYellow {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LightYellow")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LightYellow", value);
        }
    }
    
    public static global::Aurora.Colour Lime {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Lime")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Lime", value);
        }
    }
    
    public static global::Aurora.Colour LimeGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("LimeGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("LimeGreen", value);
        }
    }
    
    public static global::Aurora.Colour Linen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Linen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Linen", value);
        }
    }
    
    public static global::Aurora.Colour Magenta {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Magenta")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Magenta", value);
        }
    }
    
    public static global::Aurora.Colour Maroon {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Maroon")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Maroon", value);
        }
    }
    
    public static global::Aurora.Colour MediumAquamarine {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumAquamarine")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumAquamarine", value);
        }
    }
    
    public static global::Aurora.Colour MediumBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumBlue", value);
        }
    }
    
    public static global::Aurora.Colour MediumOrchid {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumOrchid")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumOrchid", value);
        }
    }
    
    public static global::Aurora.Colour MediumPurple {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumPurple")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumPurple", value);
        }
    }
    
    public static global::Aurora.Colour MediumSeaGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumSeaGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumSeaGreen", value);
        }
    }
    
    public static global::Aurora.Colour MediumSlateBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumSlateBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumSlateBlue", value);
        }
    }
    
    public static global::Aurora.Colour MediumSpringGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumSpringGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumSpringGreen", value);
        }
    }
    
    public static global::Aurora.Colour MediumTurquoise {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumTurquoise")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumTurquoise", value);
        }
    }
    
    public static global::Aurora.Colour MediumVioletRed {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MediumVioletRed")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MediumVioletRed", value);
        }
    }
    
    public static global::Aurora.Colour MidnightBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MidnightBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MidnightBlue", value);
        }
    }
    
    public static global::Aurora.Colour MColourCream {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MColourCream")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MColourCream", value);
        }
    }
    
    public static global::Aurora.Colour MistyRose {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("MistyRose")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MistyRose", value);
        }
    }
    
    public static global::Aurora.Colour Moccasin {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Moccasin")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Moccasin", value);
        }
    }
    
    public static global::Aurora.Colour NavajoWhite {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("NavajoWhite")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("NavajoWhite", value);
        }
    }
    
    public static global::Aurora.Colour Navy {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Navy")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Navy", value);
        }
    }
    
    public static global::Aurora.Colour OldLace {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("OldLace")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("OldLace", value);
        }
    }
    
    public static global::Aurora.Colour Olive {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Olive")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Olive", value);
        }
    }
    
    public static global::Aurora.Colour OliveDrab {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("OliveDrab")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("OliveDrab", value);
        }
    }
    
    public static global::Aurora.Colour Orange {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Orange")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Orange", value);
        }
    }
    
    public static global::Aurora.Colour OrangeRed {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("OrangeRed")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("OrangeRed", value);
        }
    }
    
    public static global::Aurora.Colour Orchid {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Orchid")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Orchid", value);
        }
    }
    
    public static global::Aurora.Colour PaleGoldenrod {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PaleGoldenrod")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PaleGoldenrod", value);
        }
    }
    
    public static global::Aurora.Colour PaleGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PaleGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PaleGreen", value);
        }
    }
    
    public static global::Aurora.Colour PaleTurquoise {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PaleTurquoise")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PaleTurquoise", value);
        }
    }
    
    public static global::Aurora.Colour PaleVioletRed {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PaleVioletRed")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PaleVioletRed", value);
        }
    }
    
    public static global::Aurora.Colour PapayaWhip {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PapayaWhip")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PapayaWhip", value);
        }
    }
    
    public static global::Aurora.Colour PeachPuff {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PeachPuff")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PeachPuff", value);
        }
    }
    
    public static global::Aurora.Colour Peru {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Peru")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Peru", value);
        }
    }
    
    public static global::Aurora.Colour Pink {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Pink")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Pink", value);
        }
    }
    
    public static global::Aurora.Colour Plum {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Plum")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Plum", value);
        }
    }
    
    public static global::Aurora.Colour PowderBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("PowderBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("PowderBlue", value);
        }
    }
    
    public static global::Aurora.Colour Purple {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Purple")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Purple", value);
        }
    }
    
    public static global::Aurora.Colour Red {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Red")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Red", value);
        }
    }
    
    public static global::Aurora.Colour RosyBrown {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("RosyBrown")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("RosyBrown", value);
        }
    }
    
    public static global::Aurora.Colour RoyalBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("RoyalBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("RoyalBlue", value);
        }
    }
    
    public static global::Aurora.Colour SaddleBrown {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SaddleBrown")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SaddleBrown", value);
        }
    }
    
    public static global::Aurora.Colour Salmon {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Salmon")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Salmon", value);
        }
    }
    
    public static global::Aurora.Colour SandyBrown {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SandyBrown")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SandyBrown", value);
        }
    }
    
    public static global::Aurora.Colour SeaGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SeaGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SeaGreen", value);
        }
    }
    
    public static global::Aurora.Colour Seashell {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Seashell")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Seashell", value);
        }
    }
    
    public static global::Aurora.Colour Sienna {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Sienna")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Sienna", value);
        }
    }
    
    public static global::Aurora.Colour Silver {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Silver")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Silver", value);
        }
    }
    
    public static global::Aurora.Colour SkyBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SkyBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SkyBlue", value);
        }
    }
    
    public static global::Aurora.Colour SlateBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SlateBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SlateBlue", value);
        }
    }
    
    public static global::Aurora.Colour SlateGray {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SlateGray")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SlateGray", value);
        }
    }
    
    public static global::Aurora.Colour Snow {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Snow")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Snow", value);
        }
    }
    
    public static global::Aurora.Colour SpringGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SpringGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SpringGreen", value);
        }
    }
    
    public static global::Aurora.Colour SteelBlue {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("SteelBlue")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("SteelBlue", value);
        }
    }
    
    public static global::Aurora.Colour Tan {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Tan")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Tan", value);
        }
    }
    
    public static global::Aurora.Colour Teal {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Teal")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Teal", value);
        }
    }
    
    public static global::Aurora.Colour Thistle {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Thistle")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Thistle", value);
        }
    }
    
    public static global::Aurora.Colour Tomato {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Tomato")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Tomato", value);
        }
    }
    
    public static global::Aurora.Colour Turquoise {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Turquoise")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Turquoise", value);
        }
    }
    
    public static global::Aurora.Colour Violet {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Violet")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Violet", value);
        }
    }
    
    public static global::Aurora.Colour Wheat {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Wheat")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Wheat", value);
        }
    }
    
    public static global::Aurora.Colour White {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("White")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("White", value);
        }
    }
    
    public static global::Aurora.Colour WhiteSmoke {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("WhiteSmoke")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("WhiteSmoke", value);
        }
    }
    
    public static global::Aurora.Colour Yellow {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("Yellow")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("Yellow", value);
        }
    }
    
    public static global::Aurora.Colour YellowGreen {
        get {
            global::Aurora.Colour ret = ((global::Aurora.Colour)(m_privateType.GetStaticField("YellowGreen")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("YellowGreen", value);
        }
    }
    
    public static double Clamp(double x) {
        object[] args = new object[] {
                x};
        double ret = ((double)(m_privateType.InvokeStatic("Clamp", new System.Type[] {
                    typeof(double)}, args)));
        return ret;
    }
}
}
